services:
  - type: web
    name: shopline-auth
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn shopline_auth.wsgi
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
